version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    build:
      context: .
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Sup3r-S3cr3t"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
